activityLog.subject.link=Закреплено «{NOTE_NAME}»
activityLog.subject.new=Создана новая заметка "{NOTE_NAME}"
activityLog.error=Ошибка при создании протокола работы

dialog.choice.ok=ОК
dialog.choice.cancel=Отмена
dialog.title=Evernote для Salesforce

linkedNotes.error.cardMeta=Ошибка при получении данных о закрепленных заметках.
linkedNotes.error.copyNote.newBizTag=Ошибка при создании метки в бизнес-аккаунте "{TAG_NAME}".
linkedNotes.error.copyNote.noteRetrieval=Ошибка при получении содержимого заметки.
linkedNotes.error.copyNote.personalTagsRetrieval=Ошибка при получении метки а личном аккаунте.
linkedNotes.error.createNote.notebookRights=У вас нет прав на создание новой заметки в выбранном блокноте.
linkedNotes.error.createNote.failure=Ошибка при создании новой заметки.
linkedNotes.error.link=Ошибка при попытке закрепить заметку.
linkedNotes.error.linkCompletion=Не удалось завершить закрепление заметки.
linkedNotes.error.sharing.failure=Ошибка при открытии доступа к заметке для компании.
linkedNotes.error.tag.guid=Ошибка при получении метки по ее идентификатору.
linkedNotes.error.tag.note=Ошибка при получении меток для заметки.
linkedNotes.error.tag.listRetrieval=Ошибка при получении списка меток.
linkedNotes.error.title.update=Ошибка при редактировании названия.
linkedNotes.error.unlink=Ошибка при попытке открепить заметку.
linkedNotes.error.noViewing=У вас не прав на просмотр этой заметки.
linkedNotes.info.noteCopied=Ваша заметка скопирована в бизнес-блокнот по умолчанию.
linkedNotes.note.none.header=Нет закрепленных заметок
linkedNotes.note.none.instructions=Искать заметки для закрепления в {RECORD_NAME}. При просмотре записи Salesforce каждый сможет просмотреть актуальную информацию о ней из Evernote.
linkedNotes.note.count={N_PLURAL:{N} заметка закреплена|{N} заметки закреплены|{N} заметок закреплено} в {RECORD_NAME}
linkedNotes.warning.unlinking=Вы собираетесь открепить заметку от {RECORD_NAME}. Продолжить?
linkedNotes.warning.noSharing=Владелец заметки не предоставил вам право открывать совместный доступ. Пользователи, не имеющие доступа, не смогут посмотреть закрепленную заметку.

linkOptions.unlink=Открепить заметку
linkOptions.linkToOthers=Закрепить в друой записи Salesforce
linkOptions.otherRecords=Другие записи

notecard.link=Закрепить эту заметку, чтобы другие могли просматривать ее в Salesforce
notecard.unlink=Открепить заметку от {RECORD_NAME}

notice.error.blurb=Вы столкнулись со следующей ошибкой:
notice.error.button.reauth=Авторизовать повторно
notice.error.button.signIn=Войти в систему
notice.error.button.tryAgain=Повторить попытку
notice.error.notEnoughHeight=Пожалуйста, попросите администратора Salesforce задать высоту этой страницы Evernote Visualforce в 480 пикселей (минимум).
notice.error.reauthBlurb=Если проблема не решится, попробуйте повторно авторизовать соединение с Evernote.
notice.error.title=Возникла проблема
notice.initial.appIntro=Недавно присоединились к Evernote? Узнать подробности об Evernote для Salesforce.
notice.initial.blurb=Подключите Evernote для Salesforce, чтобы запускать проекты с коллегами и хранить заметки и записи в одном месте.
notice.initial.button=Подключить
notice.initial.title=Единое рабочее пространство

operation.error.notFound=Запись Salesforce "{RECORD_NAME}" типа {RECORD_TYPE} не обнаружена.

popup.error.blocker=Блокировщик всплывающих окон обнаружен. Пожалуйста, разрешите всплывающие окна Salesforce в вашем браузере.
popup.error.linkedNoteGuids=Не удалось получить список закрепленных заметок.
popup.error.noThrift=Извините, возникла ошибка. Пожалуйста, перегрузите окно.
popup.error.salesforceName=Не удалось получить название записи Salesforce.

relatedNotes.error.couldNotFind=Ошибка при поиске связанных заметок.
relatedNotes.note.notRelated=Заметка не связана
relatedNotes.status.none=Похожих заметок не найдено
relatedNotes.status.count=Показать {N_PLURAL:{N} связанную заметку|{N} связанных заметки|{N} связанных заметок}

search.dropdown.business=Бизнес
search.dropdown.personal=Личный
search.notes.error=Возникла ошибка при поиске заметок.
search.notes.none=Нет результатов поиска
search.notes.onlymine=Создано мной
search.notes.withinJoinedNotebooks=В подключенных блокнотах
search.notes.allViewable=Все доступные
search.notes.recent=Недавние заметки
search.notes.found={N_PLURAL:Найдена {N} заметка|Найдено {N} заметки|Найдено {N} заметок}
search.tips.intro=Советы для поиска
search.tips.tip0=Поиск не зависит от регистра
search.tips.tip1=При поиске нескольких слов будут найдены только заметки, содержащие все слова
search.tips.tip2=Используйте кавычки для поиска всех заданных слов -
search.tips.tip3=Используйте звездочку в конце слова для поиска специальных символов -
search.tips.tip4=Используйте <b>tag:</b> для поиска заметок по метке. Можно использовать специальный символ -
search.tips.tip5=Используйте <b>notebook:</b> для поиска заметок в блокноте. Требуется точное совпадение -
search.tips.tip6=Используйте <b>intitle:</b> для поиска заголовка -
search.tips.tip7=Используйие <b>author:</b> для поиска по создателю -
search.tips.tip8=Советы можно комбинировать -
search.tips.example.tip2="Гроздья гнева"
search.tips.example.tip3=мобильное приложение*
search.tips.example.tip4=tag:супер*, tag:супермен
search.tips.example.tip5=notebook:"мой блокнот"
search.tips.example.tip6=intitle:курица
search.tips.example.tip7=author:иван*, author:"иван петров"
search.tips.example.tip8=tag:супер* мибильный
search.wait=Идет поиск...

sidemenu.nav.linkedNotes=Посмотреть закрепленные заметки
sidemenu.nav.newNote=Создать новую заметку
sidemenu.nav.relatedNotes=Посмотреть связанные заметки
sidemenu.nav.search=Поиск заметок
sidemenu.user.about=Об Evernote для Salesforce
sidemenu.user.help=Справка
sidemenu.user.defaultNotebook.error.noRecord=Попытка создать блокнот по умолчанию. У пользователя нет токена доступа.
sidemenu.user.defaultNotebook.error.notebookUpdate=Ошибка при обновлении блокнота по умолчанию.
sidemenu.user.defaultNotebook.error.notebookRetrieval=Появилась ошибка при извлечении блокнотов.
sidemenu.user.defaultNotebook.instruction=Выбрать новый блокнот:
sidemenu.user.defaultNotebook.menu=Изменить блокнот по умолчанию
sidemenu.user.defaultNotebook.noNotebook=Пожалуйста, выберите блокнот по умолчанию
sidemenu.user.defaultNotebook.state=Ваш блокнот по умолчанию
sidemenu.user.defaultNotebook.explanation=При создании новой заметки она будет автоматически сохраняться в этот блокнот.
sidemenu.user.disconnect.confirm=Вы уверены, что хотите отключить аккаунт Evernote от Salesforce? Вы можете переподключить его в любое время.
sidemenu.user.disconnect.menu=Отключить Evernote
sidemenu.user.openEvernote=Открыть Evernote
sidemenu.user.version=Версия {VERSION_NUMBER}

sso.proceed.disconnect=Вы не хотели авторизоваться с {EMAIL}? Отключить Evernote
sso.proceed.failure=Повторить попытку
sso.proceed.initial=Продолжить
sso.proceed.wait=Пожалуйста, подождите
sso.title.failure=Ошибка единого входа. Хотите повторить попытку?
sso.title.initial=Для продолжения работы Evernote для Salesforce требуется единый вход.

timespan.count={N_PLURAL:{N} {TIMEUNIT:секунду|минуту|час|день|неделю}|{N} {TIMEUNIT:секунд|минуты|часа|дня|недели}|{N} {TIMEUNIT:секунд|минут|часов|дней|недель}} назад
timespan.lastWeek=На прошлой неделе
timespan.moments=Секунду назад
timespan.today=Сегодня
timespan.yesterday=Вчера

token.error.businessAccountRequired=Необходимо использовать аккаунт Evernote Business, указанный вашим администратором Salesforce.
token.error.businessToken=Ошибка аутентификации в бизнес-аккаунте.
token.error.catchAll=Ошибка аунтентификации.
token.error.disabled=Администратор Evernote отключил Evernote для Salesforce.
token.error.invalidLongToken=Переподключить Evernote к Salesforce: авторизуйтесь повторно.
token.error.legacySso=Аутентификация SSO не удалась.
token.error.missingLongToken=Нет подключения к Evernote. Пожалуйста, подключитесь к Evernote.
token.error.noRecordForStorePath=Не существует токена пользователя, однако зафиксирована попытка обновить путь к хранилищу пользователя.
token.error.popupSsoNoOpener=Ваш браузер не позволяет единый вход. Пожалуйста, используйте браузер, который поддерживает window.opener.
token.error.sessionAuth=Авторизация к сессии Evernote не удалась.
token.error.serverError=Временная ошибка сервера. Пожалуйста, попробуйте еще раз.
token.error.shortToken=Не удалось создать токен Evernote.
token.error.shortTokenCreate=Ошибка при открытии новой сессии Evernote.
token.error.userInfo=Не удалось получить информацию о пользователе.
token.error.userUrls=Не удалось получить URL пользователя.
token.error.webResources=Не удалось открыть сессию веб-рексурсов Evernote.