activityLog.subject.link="{NOTE_NAME}" vastgepind
activityLog.subject.new=Maakte nieuwe notitie "{NOTE_NAME}"
activityLog.error=Er is een fout opgetreden bij het aanmaken van een Activiteitenlogboek

dialog.choice.ok=OK
dialog.choice.cancel=Annuleer
dialog.title=Evernote voor Salesforce

linkedNotes.error.cardMeta=Er is een fout opgetreden bij het ophalen van de details van je vastgepinde notities.
linkedNotes.error.copyNote.newBizTag=Er is een fout opgetreden bij het aanmaken van het nieuwe zakelijke label "{TAG_NAME}".
linkedNotes.error.copyNote.noteRetrieval=Er is een fout opgetreden bij het ophalen van de notitiecontent.
linkedNotes.error.copyNote.personalTagsRetrieval=Er is een fout opgetreden bij het ophalen van een persoonlijk label.
linkedNotes.error.createNote.notebookRights=Je hebt geen rechten om in een nieuwe notitie te schrijven in het geselecteerde notitieboek.
linkedNotes.error.createNote.failure=Er is een fout opgetreden bij het aanmaken van een nieuwe notitie.
linkedNotes.error.link=Er is een fout opgetreden bij het vastpinnen van een notitie.
linkedNotes.error.linkCompletion=Het vastpinnen van je notitie kan niet afgemaakt worden.
linkedNotes.error.sharing.failure=Er is een fout opgetreden bij het delen van de notitie met het bedrijf.
linkedNotes.error.tag.guid=Er is een fout opgetreden bij het ophalen van een label door een id.
linkedNotes.error.tag.note=Er is een fout opgetreden bij het ophalen van notitielabels.
linkedNotes.error.tag.listRetrieval=Er is een fout opgetreden bij het ophalen van de labellijst.
linkedNotes.error.title.update=Er is een fout geconstateerd bij het updaten van de titel.
linkedNotes.error.unlink=Er is een fout opgetreden bij het losmaken van een notitie.
linkedNotes.error.noViewing=Je bent niet bevoegd om deze notitie te bekijken.
linkedNotes.info.noteCopied=Je notitie is gekopieerd naar je standaard zakelijke notitieboek.
linkedNotes.note.none.header=Er zijn nog geen vastgepinde notities
linkedNotes.note.none.instructions=Zoek naar notities om vast te pinnen in {RECORD_NAME}. Iedereen die dit Salesforce document bekijkt, ziet relevante informatie uit Evernote.
linkedNotes.note.count={N_PLURAL:{N} notitie is|{N} notities} zijn vastgepind aan {RECORD_NAME}
linkedNotes.warning.unlinking=Je wil deze notitie losmaken uit {RECORD_NAME}. Wil je verder gaan?
linkedNotes.warning.noSharing=De eigenaar van deze notitie heeft je geen toestemming gegeven om de notitie te delen. Gebruikers zonder toegang kunnen deze vastgepinde notitie niet zien.

linkOptions.unlink=Maak notitie los
linkOptions.linkToOthers=Pin vast aan andere Salesforce documenten
linkOptions.otherRecords=Andere documenten

notecard.link=Pin deze notitie vast zodat iedereen het in Salesforce kan zien
notecard.unlink=Maak notitie los van {RECORD_NAME}

notice.error.blurb=Je bent de volgende foutmelding tegengekomen:
notice.error.button.reauth=Herautoriseer
notice.error.button.signIn=Inloggen
notice.error.button.tryAgain=Probeer opnieuw
notice.error.notEnoughHeight=Laat je Salesforce beheerder weten om de waarde van deze Evernote Visualforce pagina op minimaal 480 pixels te zetten.
notice.error.reauthBlurb=Als je problemen blijft ervaren, probeer je verbinding met Evernote dan opnieuw te autoriseren.
notice.error.title=Er is een fout opgetreden
notice.initial.appIntro=Nieuw bij Evernote? Ontdek meer over Evernote voor Salesforce.
notice.initial.blurb=Gebruik Evernote voor Salesforce om projecten met je team te starten en houd je notities en verslagen op één plek.
notice.initial.button=Verbinding maken
notice.initial.title=Eén werkplek

operation.error.notFound=Salesforce document "{RECORD_NAME}" van het type {RECORD_TYPE} is niet gevonden.

popup.error.blocker=Popupblocker gevonden. Stel je browser zo in dat popups van Salesforce toegestaan worden.
popup.error.linkedNoteGuids=Er kan geen lijst van vastgepinde notities opgehaald worden.
popup.error.noThrift=Er is helaas een fout opgetreden. Herlaad dit venster.
popup.error.salesforceName=De naam van het Salesforce document kan niet opgehaald worden.

relatedNotes.error.couldNotFind=Er is een fout opgetreden bij het vinden van gerelateerde notities.
relatedNotes.note.notRelated=Deze notitie is hier niet aan gerelateerd
relatedNotes.status.none=Geen gerelateerde notities gevonden
relatedNotes.status.count=Er {N_PLURAL:wordt{N} gerelateerde notitie|worden {N} gerelateerde notities} getoond

search.dropdown.business=Business
search.dropdown.personal=Privé
search.notes.error=Er is een fout opgetreden bij het zoeken naar notities.
search.notes.none=Er zijn geen zoekresultaten
search.notes.onlymine=Aangemaakt door mij
search.notes.withinJoinedNotebooks=In notitieboeken waar je lid van bent
search.notes.allViewable=Allemaal zichtbaar
search.notes.recent=Meest recente notities
search.notes.found={N_PLURAL:{N} notitie|{N} notities} gevonden
search.tips.intro=Zoektips
search.tips.tip0=Zoek met hoofdlettergoeligheid
search.tips.tip1=Waneer je op verschillende woorden zoekt, worden alleen de notities getoond die alle woorden bevatten
search.tips.tip2=Gebruik aanhalingstekens voor dezelfde forumerling van die woorden -
search.tips.tip3=Gebruik een asterisk aan het eind van een woord voor wildcard zoeken -
search.tips.tip4=Gebruik <b>tag:</b> (label) om naar notities te zoeken op basis van een label. Je kan ook een wildcard gebruiken -
search.tips.tip5=Gebruik <b>notebook:</b> (notitieboek) om naar notities in een notitieboek te zoeken. Preciese formulering is vereist -
search.tips.tip6=Gebruik <b>intitle:</b> (titel) om op basis van titel te zoeken -
search.tips.tip7=Gebruik <b>author:</b> (auteur) om op basis van de auteur te zoeken -
search.tips.tip8=Tips kunnen gecombineerd worden -
search.tips.example.tip2="Druiven der gramschap"
search.tips.example.tip3=mobiele app*
search.tips.example.tip4=tag:super*. tag:superman
search.tips.example.tip5=notebook:"mijn notitieboek"
search.tips.example.tip6=intitle:kip
search.tips.example.tip7=author:susan*, author:"susan carter"
search.tips.example.tip8=tag:super* mobiel
search.wait=Aan het zoeken...

sidemenu.nav.linkedNotes=Bekijk vastgepinde notities
sidemenu.nav.newNote=Maak een nieuwe notitie
sidemenu.nav.relatedNotes=Bekijk gerelateerde notities
sidemenu.nav.search=Zoek naar notities
sidemenu.user.about=Over Evernote voor Salesforce
sidemenu.user.help=Help
sidemenu.user.defaultNotebook.error.noRecord=Stel een standaardnotitieboek in. De gebruiker heeft geen toegangstoken.
sidemenu.user.defaultNotebook.error.notebookUpdate=Er is een fout bij het updaten van het standaardnotitieboek.
sidemenu.user.defaultNotebook.error.notebookRetrieval=Er is een fout opgetreden bij het ophalen van notitieboeken.
sidemenu.user.defaultNotebook.instruction=Nieuw notitieboek selecteren:
sidemenu.user.defaultNotebook.menu=Wijzig standaardnotitieboek
sidemenu.user.defaultNotebook.noNotebook=Selecteer een standaardnotitieboek
sidemenu.user.defaultNotebook.state=Jouw standaardnotitieboek
sidemenu.user.defaultNotebook.explanation=Wanneer je een nieuwe notitie aanmaakt, wordt het automatisch in dit notitieboek opgeslagen.
sidemenu.user.disconnect.confirm=Weet je zeker dat je Evernote wil ontkoppelen van Salesforce? Je kan het altijd weer koppelen.
sidemenu.user.disconnect.menu=Verbreek verbinding met Evernote
sidemenu.user.openEvernote=Open Evernote
sidemenu.user.version=Versie {VERSION_NUMBER}

sso.proceed.disconnect=Probeer je niet in te loggen met {EMAIL}? Verbreek dan de verbinding met Evernote
sso.proceed.failure=Probeer opnieuw
sso.proceed.initial=Ga verder
sso.proceed.wait=Even geduld a.u.b
sso.title.failure=Single Sign In autenticatie is mislukt. Opnieuw proberen?
sso.title.initial=Single Sign In is vereist om Evernote voor Salersforce te gebruiken.

timespan.count={N_PLURAL:{N} {TIMEUNIT:seconde|minuut|uur|dag|week}|{N} {TIMEUNIT:seconden|minuten|uur|dagen|weken}} geleden
timespan.lastWeek=Vorige week
timespan.moments=Even geleden
timespan.today=Vandaag
timespan.yesterday=Gisteren

token.error.businessAccountRequired=Je moet een Evernote Business account gebruiken, vastgesteld door je Salesforce beheerder.
token.error.businessToken=Er is een fout opgetreden bij het initiëren van een zakelijke authenticatie.
token.error.catchAll=Er is een fout opgetreden tijdens de authenticatie.
token.error.disabled=Je Evernote beheerder heeft Evernote voor Salesforce uitgeschakeld.
token.error.invalidLongToken=Koppel Evernote en Salesforce door opnieuw in te loggen.
token.error.legacySso=SSO authenticatie verouderde software mislukt.
token.error.missingLongToken=Er is geen verbinding met Evernote. Initieer je verbinding met Evernote.
token.error.noRecordForStorePath=Er bestaat geen gebruikerstoken. We proberen het opslag pad van de gebruiker te updaten.
token.error.popupSsoNoOpener=Je browser voorkomt het gebruik van de vereiste Single Sign On. Gebruik een browser die window.opener ondersteunt.
token.error.sessionAuth=Authenticatie Evernote sessie mislukt.
token.error.serverError=Er is een tijdelijke serveerfout. Probeer het opnieuw.
token.error.shortToken=Initiëren Evernote token mislukt.
token.error.shortTokenCreate=Er is een fout opgetreden bij het openen van een nieuwe Evernote sessie.
token.error.userInfo=Je gebruikersgegevens kunnen niet opgehaald worden.
token.error.userUrls=De gebruikersurls kunnen niet opgehaald worden.
token.error.webResources=Het openen van de Evernote webbronnen is mislukt.