activityLog.subject.link=Pinnet "{NOTE_NAME}"
activityLog.subject.new=Oprettede ny note "{NOTE_NAME}"
activityLog.error=Fejl under oprettelse af ​​en aktivitetslog

dialog.choice.ok=OK
dialog.choice.cancel=Annuller
dialog.title=Evernote til Salesforce

linkedNotes.error.cardMeta=Fejl under hentning af detaljer på dine pinnede noter.
linkedNotes.error.copyNote.newBizTag=Fejl ved oprettelse af nyt Business-mærke "{TAG_NAME}".
linkedNotes.error.copyNote.noteRetrieval=Fejl ved hentning af noteindhold.
linkedNotes.error.copyNote.personalTagsRetrieval=Fejl ved hentning af et personligt mærke.
linkedNotes.error.createNote.notebookRights=Du har ikke tilladelse til at skrive en ny note til din valgte notesbog.
linkedNotes.error.createNote.failure=Fejl under oprettelse af en ny note.
linkedNotes.error.link=Fejl under forsøg på at pinne en note.
linkedNotes.error.linkCompletion=Kunne ikke afslutte pinning af din note.
linkedNotes.error.sharing.failure=Der opstod en fejl ved at deling af noten med virksomheden.
linkedNotes.error.tag.guid=Fejl under hentning af et mærke med et ID.
linkedNotes.error.tag.note=Fejl under hentning af notemærker.
linkedNotes.error.tag.listRetrieval=Fejl ved hentning af liste over mærker.
linkedNotes.error.title.update=Fejl under opdatering af titel.
linkedNotes.error.unlink=Fejl under forsøg på at fjerne pin fra en note.
linkedNotes.error.noViewing=Du har ikke tilladelse til at få vist denne note.
linkedNotes.info.noteCopied=Din note er blevet kopieret til din standard Business-notesbog.
linkedNotes.note.none.header=Ingen pinnede noter endnu
linkedNotes.note.none.instructions=Søg efter noter der skal pinnes til {RECORD_NAME}. Enhver der ser denne Salesforce-post vil se relevant information fra Evernote.
linkedNotes.note.count={N_PLURAL:{N} note er|{N} noter er} pinnet til {RECORD_NAME}
linkedNotes.warning.unlinking=Du er ved at fjerne pin på denne note fra {RECORD_NAME}. Vil du fortsætte?
linkedNotes.warning.noSharing=Ejeren af ​​denne note har ikke givet dig rettigheder til at dele. Brugere uden adgang vil ikke se denne pinnede note.

linkOptions.unlink=Fjern pin fra note
linkOptions.linkToOthers=Pin til andre Salesforce-poster
linkOptions.otherRecords=Andre poster

notecard.link=Pin denne note så alle kan få den vist i Salesforce
notecard.unlink=Fjern pin fra note fra {RECORD_NAME}

notice.error.blurb=Du er stødt på følgende fejl:
notice.error.button.reauth=Godkend igen
notice.error.button.signIn=Log på
notice.error.button.tryAgain=Prøv igen
notice.error.notEnoughHeight=Giv venligst din Salesforce-administrator besked om at indstille højden på ​​denne Evernote Visualforce-side til mindst 480 pixel.
notice.error.reauthBlurb=Hvis problemerne fortsætter kan du prøve at godkende din forbindelse til Evernote igen.
notice.error.title=Vi er stødt på et problem
notice.initial.appIntro=Er du ny bruger af Evernote? Få mere at vide om Evernote til Salesforce.
notice.initial.blurb=Tilslut Evernote til Salesforce for at starte projekter med dit team og gem dine noter og optegnelser på et sted.
notice.initial.button=Opret forbindelse
notice.initial.title=Et arbejdsområde

operation.error.notFound=Salesforce-post "{RECORD_NAME}" af typen {RECORD_TYPE} blev ikke fundet.

popup.error.blocker=Popup-blokerer opdaget. Indstil venligst din browser til at tillade popups fra Salesforce.
popup.error.linkedNoteGuids=Kunne ikke hente en liste over pinnede noter.
popup.error.noThrift=Beklager, der opstod en fejl. Genindlæs venligst dette vindue.
popup.error.salesforceName=Kunne ikke hente navn på Salesforce-post.

relatedNotes.error.couldNotFind=Kunne ikke finde relaterede noter.
relatedNotes.note.notRelated=Denne note er ikke relateret
relatedNotes.status.none=Der blev ikke fundet nogen relaterede noter
relatedNotes.status.count=Viser {N_PLURAL:{N} relateret note|{N} relaterede noter}

search.dropdown.business=Business
search.dropdown.personal=Personlig
search.notes.error=Der opstod en fejl ved søgning efter noter.
search.notes.none=Ingen søgeresultater
search.notes.onlymine=Oprettet af mig
search.notes.withinJoinedNotebooks=Inde i notesbøger du er tilmeldt
search.notes.allViewable=Alle synlige
search.notes.recent=Seneste noter
search.notes.found={N_PLURAL:{N} note|{N} noter} fundet
search.tips.intro=Søgetips
search.tips.tip0=Søgningen skelner ikke mellem store og små bogstaver
search.tips.tip1=Når du søger med flere ord vil der kun blive fundet noter, der indeholder alle ordene
search.tips.tip2=Brug anførselstegn for et præcist match med alle ord -
search.tips.tip3=Brug en stjerne i slutningen af ​​et ord for en wildcard-søgning -
search.tips.tip4=Brug <b>tag:</b> for at søge efter noter med et mærke. Du kan bruge et wildcard -
search.tips.tip5=Brug <b>notebook:</b> for at søge efter noter i en notesbog. Nøjagtigt match kræves -
search.tips.tip6=Brug <b>intitle:</b> for kun at søge efter titlen -
search.tips.tip7=Brug <b>author:</b> for at søge baseret på forfatteren -
search.tips.tip8=Tips kan kombineres -
search.tips.example.tip2="Vredens druer"
search.tips.example.tip3=mobil-app*
search.tips.example.tip4=mærke:super *, mærke:superman
search.tips.example.tip5=notesbog:"min notesbog"
search.tips.example.tip6=intitle:kylling
search.tips.example.tip7=forfatter:susan*, forfatter:"susan carter"
search.tips.example.tip8=mærke:super* mobil
search.wait=Søger...

sidemenu.nav.linkedNotes=Vis pinnede noter
sidemenu.nav.newNote=Opret ny note
sidemenu.nav.relatedNotes=Vis relaterede noter
sidemenu.nav.search=Søg efter noter
sidemenu.user.about=Om Evernote til Salesforce
sidemenu.user.help=Hjælp
sidemenu.user.defaultNotebook.error.noRecord=Forsøger at indstille standardnotesbog men brugeren har intet adgangstoken.
sidemenu.user.defaultNotebook.error.notebookUpdate=Fejl ved opdatering af standardnotesbog.
sidemenu.user.defaultNotebook.error.notebookRetrieval=Der opstod en fejl under hentning af notesbøger.
sidemenu.user.defaultNotebook.instruction=Vælg ny notesbog:
sidemenu.user.defaultNotebook.menu=Skift standardnotesbog
sidemenu.user.defaultNotebook.noNotebook=Vælg venligst en standardnotesbog
sidemenu.user.defaultNotebook.state=Din standardnotesbog
sidemenu.user.defaultNotebook.explanation=Når du opretter en ny note gemmes den automatisk i denne notesbog.
sidemenu.user.disconnect.confirm=Er du sikker på at du vil afbryde forbindelsen mellem din Evernote-konto og Salesforce? Du kan til enhver tid genoprette forbindelse.
sidemenu.user.disconnect.menu=Afbryd forbindelse med Evernote
sidemenu.user.openEvernote=Åbn Evernote
sidemenu.user.version=Version {VERSION_NUMBER}

sso.proceed.disconnect=Forsøgte du ikke at logge ind med {EMAIL}? Afbryd forbindelse med Evernote
sso.proceed.failure=Prøv igen
sso.proceed.initial=Fortsæt
sso.proceed.wait=Vent
sso.title.failure=Godkendelse med enkeltlogon mislykkedes. Prøv igen?
sso.title.initial=Enkeltlogon er påkrævet for at fortsætte med at bruge Evernote til Salesforce.

timespan.count={N_PLURAL:{N} {TIMEUNIT:sekund|minut|time|dag|uge}|{N} {TIMEUNIT:sekunder|minutter|timer|dage|uger}} siden
timespan.lastWeek=Sidste uge
timespan.moments=Øjeblik siden
timespan.today=I dag
timespan.yesterday=I går

token.error.businessAccountRequired=Du skal bruge en Evernote Business-konto, der er specificeret af din Salesforce-administrator.
token.error.businessToken=Der opstod en fejl under initiering af virksomhedsgodkendelse.
token.error.catchAll=Der opstod en fejl under forsøg på at godkende.
token.error.disabled=Din Evernote-administrator har deaktiveret Evernote til Salesforce.
token.error.invalidLongToken=Opret forbindelse mellem Evernote og Salesforce ved at logge ind igen.
token.error.legacySso=Forældet SSO-godkendelse mislykkedes.
token.error.missingLongToken=Der er ingen Evernote-forbindelse. Start venligst din Evernote-forbindelse.
token.error.noRecordForStorePath=Der findes intet brugertoken. Forsøger at opdatere brugerens lagringssøgevej.
token.error.popupSsoNoOpener=Din browser forhindrer dit nødvendige enkeltlogon. Skift venligst til en browser, der understøtter window.opener.
token.error.sessionAuth=Kunne ikke godkende Evernote-session.
token.error.serverError=Midlertidig serverfejl. Prøv venligst igen.
token.error.shortToken=Kunne ikke starte et Evernote-token.
token.error.shortTokenCreate=Fejl under åbning af en ny Evernote-session.
token.error.userInfo=Kunne ikke hente dine brugeroplysninger.
token.error.userUrls=Kunne ikke hente dine bruger-URL's.
token.error.webResources=Kunne ikke åbne en session til Evernote-webressourcer.