activityLog.subject.link=A épinglé « {NOTE_NAME} »
activityLog.subject.new=A créé la note « {NOTE_NAME} »
activityLog.error=Une erreur s'est produite lors de la création d'un journal d'activités.

dialog.choice.ok=OK
dialog.choice.cancel=Annuler
dialog.title=Evernote pour Salesforce

linkedNotes.error.cardMeta=Une erreur s'est produite lors de la récupération d'informations sur vos notes épinglées.
linkedNotes.error.copyNote.newBizTag=Une erreur s'est produite lors de la création de l'étiquette Business « {TAG_NAME} ».
linkedNotes.error.copyNote.noteRetrieval=Une erreur s'est produite lors de la récupération du contenu de la note.
linkedNotes.error.copyNote.personalTagsRetrieval=Une erreur s'est produite lors de la récupération d'une étiquette personnelle.
linkedNotes.error.createNote.notebookRights=Vous n'êtes pas autorisé à rédiger une nouvelle note dans le carnet de notes sélectionné.
linkedNotes.error.createNote.failure=Une erreur s'est produite lors de la création de la note.
linkedNotes.error.link=Une erreur s'est produite lors de la tentative d'épinglage d'une note.
linkedNotes.error.linkCompletion=Impossible d'épingler votre note.
linkedNotes.error.sharing.failure=Une erreur s'est produite lors du partage de la note avec le compte Business.
linkedNotes.error.tag.guid=Une erreur s'est produite lors de la récupération d'une étiquette par un identifiant.
linkedNotes.error.tag.note=Une erreur s'est produite lors de la récupération des étiquettes des notes.
linkedNotes.error.tag.listRetrieval=Une erreur s'est produite lors de la récupération de la liste d'étiquettes.
linkedNotes.error.title.update=Une erreur s'est produite lors de la mise à jour du titre.
linkedNotes.error.unlink=Une erreur s'est produite lors de la tentative de désépinglage d'une note.
linkedNotes.error.noViewing=Vous n'avez pas l'autorisation de consulter cette note.
linkedNotes.info.noteCopied=Votre note a été copiée dans votre carnet de notes Business par défaut.
linkedNotes.note.none.header=Il n'y a aucune note épinglée pour l'instant
linkedNotes.note.none.instructions=Recherchez des notes à épingler à {RECORD_NAME}. Toutes les personnes qui ont accès à cet enregistrement Salesforce verront des informations pertinentes d'Evernote.
linkedNotes.note.count={N_PLURAL:{N} note est épinglée|{N} notes sont épinglées} à {RECORD_NAME}
linkedNotes.warning.unlinking=Vous êtes sur le point de désépingler cette note de {RECORD_NAME}. Continuer ?
linkedNotes.warning.noSharing=Le propriétaire de cette note ne vous a pas donné l'autorisation de la partager. Les utilisateurs sans accès ne pourront pas voir la note épinglée.

linkOptions.unlink=Désépingler la note
linkOptions.linkToOthers=Épingler à d'autres enregistrements Salesforce
linkOptions.otherRecords=Autres enregistrements

notecard.link=Épinglez cette note pour que tout le monde puisse la voir dans Salesforce
notecard.unlink=Désépingler la note de {RECORD_NAME}

notice.error.blurb=Vous avez rencontré l'erreur suivante :
notice.error.button.reauth=Autoriser à nouveau
notice.error.button.signIn=Se connecter
notice.error.button.tryAgain=Réessayer
notice.error.notEnoughHeight=Veuillez demander à votre administrateur Salesforce de définir la taille de cette page Evernote Visualforce sur 480 pixels minimum.
notice.error.reauthBlurb=Si les problèmes persistent, tentez d'autoriser à nouveau votre connexion à Evernote.
notice.error.title=Nous avons rencontré un problème
notice.initial.appIntro=Nouveau sur Evernote ? Apprenez-en plus sur Evernote pour Salesforce.
notice.initial.blurb=Connectez-vous à Evernote pour Salesforce pour lancer des projets avec votre équipe et conserver vos notes et enregistrements en un seul et même endroit.
notice.initial.button=Connecter
notice.initial.title=Un espace de travail

operation.error.notFound=L'enregistrement Salesforce « {RECORD_NAME} » de type {RECORD_NAME} est introuvable.

popup.error.blocker=Un bloqueur de fenêtres publicitaires a été détecté. Veuillez autoriser les fenêtres publicitaires de Salesforce dans votre navigateur.
popup.error.linkedNoteGuids=Impossible d'obtenir une liste des notes épinglées
popup.error.noThrift=Désolé, une erreur s'est produite. Veuillez recharger cette fenêtre.
popup.error.salesforceName=Impossible d'obtenir le nom de l'enregistrement Salesforce

relatedNotes.error.couldNotFind=Une erreur s'est produite lors de la recherche de notes liées.
relatedNotes.note.notRelated=Cette note n'est pas liée
relatedNotes.status.none=Aucune note connexe trouvée
relatedNotes.status.count=Affichage de {N_PLURAL:{N} note liée|{N} notes liées}

search.dropdown.business=Business
search.dropdown.personal=Personnel
search.notes.error=Une erreur s'est produite lors de la recherche de notes.
search.notes.none=Aucun résultat de recherche
search.notes.onlymine=Créé par moi
search.notes.withinJoinedNotebooks=Dans les carnets de notes rejoints
search.notes.allViewable=Toutes les notes consultables
search.notes.recent=Notes les plus récentes
search.notes.found={N_PLURAL:{N} note trouvée|{N} notes trouvées}
search.tips.intro=Astuces pour la recherche
search.tips.tip0=La recherche ne tient pas compte de la casse.
search.tips.tip1=Si vous utilisez plusieurs mots dans votre recherche, seules les notes qui contiennent tous les mots seront trouvées.
search.tips.tip2=Utilisez des guillemets pour rechercher une expression précise -
search.tips.tip3=Utilisez un astérisque à la fin d'un mot pour faire une recherche par caractères génériques -
search.tips.tip4=Utilisez <b>tag:</b> pour rechercher des notes par étiquette. Vous pouvez utiliser un caractère générique -
search.tips.tip5=Utilisez <b>notebook:</b> pour chercher des notes dans un carnet de notes. Correspondance exacte requise -
search.tips.tip6=Utilisez <b>intitle:</b> pour chercher uniquement le titre -
search.tips.tip7=Utilisez <b>author:</b> pour faire des recherches par auteur -
search.tips.tip8=Vous pouvez combiner ces conseils -
search.tips.example.tip2="Les Raisins de la colère"
search.tips.example.tip3=application mobile*
search.tips.example.tip4=tag:super*, tag:superman
search.tips.example.tip5=notebook:"mon carnet de notes"
search.tips.example.tip6=intitle:poulet
search.tips.example.tip7=author:susan*, author:"susan carter"
search.tips.example.tip8=tag:super* mobile
search.wait=Recherche en cours

sidemenu.nav.linkedNotes=Voir les notes épinglées
sidemenu.nav.newNote=Créer une nouvelle note
sidemenu.nav.relatedNotes=Voir les notes liées
sidemenu.nav.search=Rechercher des notes
sidemenu.user.about=À propos d'Evernote pour Salesforce
sidemenu.user.help=Aide
sidemenu.user.defaultNotebook.error.noRecord=Tentative de définition du carnet de notes par défaut, mais l'utilisateur n'a pas de jeton d'accès.
sidemenu.user.defaultNotebook.error.notebookUpdate=Une erreur s'est produite lors de la mise à jour du carnet de notes par défaut.
sidemenu.user.defaultNotebook.error.notebookRetrieval=Une erreur s'est produite lors de la récupération des carnets de notes.
sidemenu.user.defaultNotebook.instruction=Sélectionner un nouveau carnet de notes :
sidemenu.user.defaultNotebook.menu=Modifier le carnet de notes par défaut
sidemenu.user.defaultNotebook.noNotebook=Sélectionnez un carnet de notes par défaut
sidemenu.user.defaultNotebook.state=Votre carnet de notes par défaut
sidemenu.user.defaultNotebook.explanation=Lorsque vous créerez une note, celle-ci sera automatiquement enregistrée dans ce carnet.
sidemenu.user.disconnect.confirm=Êtes-vous sûr de vouloir déconnecter votre compte Evernote de Salesforce ? Vous pouvez vous reconnecter à tout moment.
sidemenu.user.disconnect.menu=Déconnecter Evernote
sidemenu.user.openEvernote=Ouvrir Evernote
sidemenu.user.version=Version {VERSION_NUMBER}

sso.proceed.disconnect=Vous ne voulez pas vous connecter avec {EMAIL} ? Déconnectez Evernote
sso.proceed.failure=Veuillez réessayer
sso.proceed.initial=Continuer
sso.proceed.wait=Veuillez patienter
sso.title.failure=L'authentification unique a échoué. Réessayer ?
sso.title.initial=L'authentification unique est requise pour continuer à utiliser Evernote pour Salesforce.

timespan.count=Il y a {N_PLURAL:{N} {TIMEUNIT:seconde|minute|heure|jour|semaine}|{N} {TIMEUNIT:secondes|minutes|heures|jours|semaines}}
timespan.lastWeek=La semaine dernière
timespan.moments=Il y a quelques minutes
timespan.today=Aujourd'hui
timespan.yesterday=Hier

token.error.businessAccountRequired=Vous devez utiliser un compte Evernote Business spécifié par votre administrateur Salesforce.
token.error.businessToken=Une erreur s'est produite lors du lancement d'une authentification Business.
token.error.catchAll=Une erreur s'est produite lors de la tentative d'authentification.
token.error.disabled=Votre administrateur Evernote a désactivé Evernote pour Salesforce.
token.error.invalidLongToken=Reconnectez Evernote et Salesforce en vous connectant à nouveau.
token.error.legacySso=L'authentification unique existante a échoué.
token.error.missingLongToken=Il n'existe aucune connexion à Evernote. Veuillez initier votre connexion à Evernote.
token.error.noRecordForStorePath=Tentative de mise à jour du chemin d'accès du magasin d'utilisateurs malgré l'absence de jeton utilisateur.
token.error.popupSsoNoOpener=Votre navigateur empêche l'opération d'authentification unique requise. Veuillez utiliser un navigateur qui prend en charge window.opener.
token.error.sessionAuth=L'authentification de la session Evernote a échoué.
token.error.serverError=Erreur serveur temporaire. Veuillez réessayer.
token.error.shortToken=Impossible d'initier un jeton Evernote
token.error.shortTokenCreate=Une erreur s'est produite lors de l'ouverture d'une nouvelle session Evernote.
token.error.userInfo=Impossible de récupérer vos informations utilisateurs
token.error.userUrls=Impossible de récupérer vos URL utilisateurs
token.error.webResources=Impossible d'ouvrir une session des ressources Web d'Evernote