activityLog.subject.link=Hai bloccato "{NOTE_NAME}"
activityLog.subject.new=Creata la nuova nota "{NOTE_NAME}"
activityLog.error=Si è verificato un errore durante la creazione di un registro attività

dialog.choice.ok=OK
dialog.choice.cancel=Annulla
dialog.title=Evernote per Salesforce

linkedNotes.error.cardMeta=Errore durante il recupero dei dettagli delle note bloccate.
linkedNotes.error.copyNote.newBizTag=Errore durante la creazione del nuovo tag business "{TAG_NAME}".
linkedNotes.error.copyNote.noteRetrieval=Errore durante il recupero dei contenuti della nota.
linkedNotes.error.copyNote.personalTagsRetrieval=Errore durante il recupero di un tag personale.
linkedNotes.error.createNote.notebookRights=Non hai il permesso di scrivere una nuova nota nel taccuino selezionato.
linkedNotes.error.createNote.failure=Errore durante la creazione di una nuova nota.
linkedNotes.error.link=Errore durante il tentativo di bloccare una nota.
linkedNotes.error.linkCompletion=Impossibile completare il blocco della nota.
linkedNotes.error.sharing.failure=Si è verificato un errore durante la condivisione della nota con l'account Business.
linkedNotes.error.tag.guid=Errore durante il recupero di un tag tramite ID.
linkedNotes.error.tag.note=Errore durante il recupero dei tag della nota.
linkedNotes.error.tag.listRetrieval=Errore durante il recupero dell'elenco dei tag.
linkedNotes.error.title.update=Errore durante l'aggiornamento del titolo.
linkedNotes.error.unlink=Errore durante il tentativo di sbloccare una nota.
linkedNotes.error.noViewing=Non hai il permesso di visualizzare questa nota.
linkedNotes.info.noteCopied=La nota è stata copiata nel tuo taccuino business principale.
linkedNotes.note.none.header=Ancora nessuna nota bloccata
linkedNotes.note.none.instructions=Cerca note da bloccare a {RECORD_NAME}. Chiunque visualizzi questo record Salesforce potrà vedere le informazioni pertinenti in Evernote.
linkedNotes.note.count={N_PLURAL:{N} nota bloccata|{N} note bloccate} a {RECORD_NAME}
linkedNotes.warning.unlinking=Stai per sbloccare questa nota da {RECORD_NAME}. Continuare?
linkedNotes.warning.noSharing=Il proprietario di questa nota non ti ha concesso i permessi di condivisione. Gli utenti senza accesso non vedranno la nota bloccata.

linkOptions.unlink=Sblocca nota
linkOptions.linkToOthers=Blocca ad altri record Salesforce
linkOptions.otherRecords=Altri record

notecard.link=Blocca questa nota in modo che tutti possano visualizzarla in Salesforce
notecard.unlink=Sblocca la nota da {RECORD_NAME}

notice.error.blurb=Si è verificato il seguente errore:
notice.error.button.reauth=Autorizza di nuovo
notice.error.button.signIn=Entra
notice.error.button.tryAgain=Riprova
notice.error.notEnoughHeight=Chiedi al tuo amministratore di Salesforce di impostare l'altezza di questa pagina di Evernote Visualforce su minimo 480 pixel.
notice.error.reauthBlurb=Se il problema persiste, prova ad autorizzare nuovamente la connessione a Evernote.
notice.error.title=Si è verificato un problema
notice.initial.appIntro=Nuovo utente di Evernote? Scopri di più su Evernote per Salesforce.
notice.initial.blurb=Connetti Evernote per Salesforce per lanciare progetti con il tuo team e tieni le tue note e record in un posto solo.
notice.initial.button=Connetti
notice.initial.title=Uno spazio di lavoro

operation.error.notFound=Impossibile trovare il record Salesforce "{RECORD_NAME}" del tipo {RECORD_TYPE}.

popup.error.blocker=Rilevato blocco popup. Imposta il browser per consentire i popup di Salesforce.
popup.error.linkedNoteGuids=Impossibile ottenere un elenco di note bloccate.
popup.error.noThrift=Spiacenti, si è verificato un errore. Ricarica la finestra.
popup.error.salesforceName=Impossibile ottenere il nome del record Salesforce.

relatedNotes.error.couldNotFind=Errore durante la ricerca delle note correlate.
relatedNotes.note.notRelated=La nota non è correlata
relatedNotes.status.none=Nessuna nota correlata trovata
relatedNotes.status.count=Visualizzazione di {N_PLURAL:{N} nota correlata|{N} note correlate}

search.dropdown.business=Business
search.dropdown.personal=Personale
search.notes.error=Si è verificato un errore durante la ricerca delle note.
search.notes.none=Nessun risultato di ricerca
search.notes.onlymine=Create da me
search.notes.withinJoinedNotebooks=Nei taccuini uniti
search.notes.allViewable=Tutte quelle visualizzabili
search.notes.recent=Note più recenti
search.notes.found={N_PLURAL:{N} nota trovata|{N} note trovate}
search.tips.intro=Consigli per la ricerca
search.tips.tip0=La funzione di ricerca non distingue tra maiuscole e minuscole
search.tips.tip1=Quando si cercano più parole, nei risultati della ricerca compaiono solo le note che contengono tutte le parole
search.tips.tip2=Per una ricerca esatta di tutte le parole, utilizza le virgolette -
search.tips.tip3=Per una ricerca con carattere jolly, utilizza un asterisco al termine della parola -
search.tips.tip4=Utilizza <b>tag:</b> per cercare le note in base ai tag. Funziona con i caratteri jolly -
search.tips.tip5=Utilizza <b>notebook:</b> per cercare le note all'interno di un taccuino. Necessaria la corrispondenza esatta -
search.tips.tip6=Utilizza <b>intitle:</b> per cercare solo nel titolo -
search.tips.tip7=Utilizza <b>author:</b> per cercare in base all'autore -
search.tips.tip8=I suggerimenti possono essere combinati -
search.tips.example.tip2="Furore"
search.tips.example.tip3=app mobile*
search.tips.example.tip4=tag:super*, tag:superman
search.tips.example.tip5=notebook:"il mio taccuino"
search.tips.example.tip6=intitle:pollo
search.tips.example.tip7=author:susanna*, author:"susanna rossi"
search.tips.example.tip8=tag:super* cellulare
search.wait=Ricerca in corso...

sidemenu.nav.linkedNotes=Visualizza note bloccate
sidemenu.nav.newNote=Crea nuova nota
sidemenu.nav.relatedNotes=Visualizza le note correlate
sidemenu.nav.search=Cerca note
sidemenu.user.about=Informazioni su Evernote per Salesforce
sidemenu.user.help=Aiuto
sidemenu.user.defaultNotebook.error.noRecord=Tentativo di impostare il taccuino principale, ma l'utente è sprovvisto di token di accesso.
sidemenu.user.defaultNotebook.error.notebookUpdate=Errore durante il caricamento del taccuino principale.
sidemenu.user.defaultNotebook.error.notebookRetrieval=Si è verificato un problema durante il recupero dei taccuini.
sidemenu.user.defaultNotebook.instruction=Seleziona nuovo taccuino:
sidemenu.user.defaultNotebook.menu=Modifica il taccuino principale
sidemenu.user.defaultNotebook.noNotebook=Seleziona un taccuino principale
sidemenu.user.defaultNotebook.state=Il tuo taccuino principale
sidemenu.user.defaultNotebook.explanation=Quando crei una nuova nota, verrà salvata automaticamente in questo taccuino.
sidemenu.user.disconnect.confirm=Vuoi disconnettere l'account Evernote da Salesforce? Puoi riconnetterlo in qualsiasi momento.
sidemenu.user.disconnect.menu=Disconnetti Evernote
sidemenu.user.openEvernote=Apri Evernote
sidemenu.user.version=Versione {VERSION_NUMBER}

sso.proceed.disconnect=Non stai provando ad accedere con {EMAIL}? Disconnetti Evernote
sso.proceed.failure=Riprova
sso.proceed.initial=Procedi
sso.proceed.wait=Prego attendi
sso.title.failure=Autenticazione Single Sing In non riuscita. Riprovare?
sso.title.initial=È richiesto il Single Sign In per continuare a utilizzare Evernote per Salesforce.

timespan.count={N_PLURAL:{N} {TIMEUNIT:secondo|minuto|ora|giorno|settimana}|{N} {TIMEUNIT:secondi|minuti|ore|giorni|settimane}} fa
timespan.lastWeek=Scorsa settimana
timespan.moments=Poco fa
timespan.today=Oggi
timespan.yesterday=Ieri

token.error.businessAccountRequired=Devi utilizzare un account Evernote Business specificato dal tuo amministratore di Salesforce.
token.error.businessToken=Errore durante l'inizializzazione di un'autenticazione Business.
token.error.catchAll=Si è verificato un errore durante il tentativo di autenticazione.
token.error.disabled=L'amministratore di Evernote ha disabilitato Evernote per Salesforce.
token.error.invalidLongToken=Riconnetti Evernote e Salesforce effettuando nuovamente l'accesso.
token.error.legacySso=Autenticazione SSO legacy non riuscita.
token.error.missingLongToken=Non esiste alcuna connessione a Evernote. Inizializza la connessione a Evernote.
token.error.noRecordForStorePath=Non esiste alcun token utente ma è in corso il tentativo di aggiornare il percorso di archiviazione utente.
token.error.popupSsoNoOpener=Il browser impedisce l'operazione di Single Sign On obbligatoria. Passa a un browser che supporta window.opener.
token.error.sessionAuth=Impossibile autenticare la sessione di Evernote.
token.error.serverError=Errore temporaneo del server. Riprova.
token.error.shortToken=Impossibile inizializzare un token.
token.error.shortTokenCreate=Errore durante l'apertura di una nuova sessione di Evernote.
token.error.userInfo=Impossibile recuperare le informazioni utente.
token.error.userUrls=Impossibile recuperare gli URL utente.
token.error.webResources=Impossibile aprire una sessione sulle risorse web Evernote.