<?xml version="1.0" encoding="UTF-8"?>
<svg width="20px" height="20px" viewBox="0 0 20 20" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 43.2 (39069) - http://www.bohemiancoding.com/sketch -->
    <title>Icons/icon-close white</title>
    <desc>Created with Sketch.</desc>
    <defs></defs>
    <g id="Symbols" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="Icons/icon-close-white">
            <path d="M11,9 L11,2 L9,2 L9,9 L2,9 L2,11 L9,11 L9,18 L11,18 L11,11 L18,11 L18,9 L11,9 Z" id="Combined-Shape" fill="#fff" transform="translate(10.000000, 10.000000) rotate(45.000000) translate(-10.000000, -10.000000) "></path>
            <rect id="Rectangle-4" fill="#FFFFFF" opacity="0" x="0" y="0" width="20" height="20"></rect>
        </g>
    </g>
</svg>