global with sharing class cc_Ava_CategoryService {

      /*  global virtual override Map<String, Object> getFieldsMap(Map<String, Object> inputData) {
        Map<String,Object> ccrzFields = super.getFieldsMap(inputData); 
         //get the fields returned by the service
        String objectFields = (String)ccrzFields.get('objectFields'); 
        objectFields += ',FeaturedProduct__c,FeaturedAddon__c';
        ccrzFields.put('objectFields', objectFields);
         return ccrzFields; 
        
    }*/
}