@isTest
public class ccCart_TriggerTest { 
    
	 

   /* @testSetup
    static void dataSetup(){
        campaign cpg=new campaign();
        cpg.name='test campaign';
        insert cpg;
    }
    static testMethod void afterInsert(){
       
        ccrz__E_Cart__c ccCart=new ccrz__E_Cart__c();
        ccCart.ccrz__BuyerEmail__c='test@Avalara.com';
        ccCart.ccrz__BuyerLastName__c='lastName';
        ccCart.ccrz__BuyerFirstName__c='firstName';
        ccCart.Campaign__c=[select Id from campaign limit 1].id;
        ccCart.ccrz__BuyerCompanyName__c='Avalara';
        insert ccCart;
       // system.assertNotEquals(NULL,ccCart.Id);
    } */
	
}